app/controllers/chat_controller.py
from flask import render_template, Blueprint, jsonify, session
from datetime import datetime, timedelta
from app.models.usuario import Usuario, db
from app.models.participante_conversa import ParticipanteConversa, db
from app.models.conversa import Conversa, db
from app.models.mensagem import Mensagem, db
from app.models.usuario_bloqueado import UsuarioBloqueado, db
from app.models.grupo import Grupo, db
from app.models.membro_grupo import MembroGrupo, db

from sqlalchemy.orm import joinedload


from app.decorador import login_obrigatorio # decorador para secao obrigatoria


chat_bp = Blueprint('chat', __name__)

@chat_bp.route('/')
def index():
    return render_template('index.html')

@chat_bp.route('/home')
@login_obrigatorio
def home():
    return render_template('home.html')
   
    
@chat_bp.route('/chat')
@login_obrigatorio
def chat():

    return render_template('chat.html')



@chat_bp.route('/conversas', methods=['GET'])
def listar_conversas():
    id_usuario_logado = session.get('id_usuario')
    
    # Filtra as conversas em que o usuário logado está envolvido
    conversas = db.session.query(ParticipanteConversa).filter(
        ParticipanteConversa.id_usuario == id_usuario_logado
    ).options(joinedload(ParticipanteConversa.conversa)).all()

    resultado = []
    
    for participante in conversas:
        # Buscar a última mensagem da conversa
        ultima_mensagem = db.session.query(Mensagem).filter(
            Mensagem.id_conversa == participante.conversa.id_conversa
        ).order_by(Mensagem.enviado_em.desc()).first()

        if ultima_mensagem:
            # Acessar o outro participante da conversa (excluindo o usuário logado)
            outro_participante = db.session.query(Usuario).join(ParticipanteConversa).filter(
                ParticipanteConversa.id_conversa == participante.conversa.id_conversa,
                ParticipanteConversa.id_usuario != id_usuario_logado
            ).first()

            if outro_participante:
                # Verificar se o outro participante está online
                tempo_agora = datetime.utcnow()
                usuario_online = False
                if outro_participante.ultimo_visto:
                    if tempo_agora - outro_participante.ultimo_visto >= timedelta(minutes=1):
                        usuario_online = True

                # Fatiar a mensagem para mostrar apenas os primeiros 10 caracteres
                mensagem_resumida = ultima_mensagem.mensagem[:10] + '...' if len(ultima_mensagem.mensagem) > 10 else ultima_mensagem.mensagem

                # Adicionar os dados da conversa à lista de resultados
                resultado.append({
                    'nome_usuario': outro_participante.nome_usuario,
                    'id_usuario': outro_participante.id_usuario,
                    'mensagem': mensagem_resumida,
                    'status': 'online' if usuario_online else 'offline',
                    'foto_perfil': outro_participante.foto_perfil,  # Supondo que você tenha um campo foto_perfil no modelo Usuario
                    'enviado_em': ultima_mensagem.enviado_em
                })

    return jsonify(resultado)


@chat_bp.route('/usuarios', methods=['GET'])
def listar_usuarios():
    usuario_logado_id = session.get('id_usuario')  # Pegando o ID do usuário logado
    
    # Subconsulta para pegar os IDs dos usuários bloqueados pelo usuário logado
    subquery_bloqueados = db.session.query(UsuarioBloqueado.id_bloqueado).filter_by(id_bloqueador=usuario_logado_id)
    
    # Consulta para pegar todos os usuários, exceto os bloqueados e o usuário logado
    usuarios = Usuario.query.filter(
        Usuario.id_usuario.notin_(subquery_bloqueados),
        Usuario.id_usuario != usuario_logado_id
    ).all()
    
    # Construindo a lista de resultados
    resultado = []
    for usuario in usuarios:
        # Verifica se o usuário está online
        status = 'online' if usuario.status == 'online' else 'offline'
        
        # Adicionando os detalhes de cada usuário à lista de resultados
        resultado.append({
            'nome_usuario': usuario.nome_usuario,
            'id_usuario': usuario.id_usuario,
            'foto_perfil': usuario.foto_perfil,  # Supondo que a coluna foto_perfil exista
            'status': status
        })
    
    return jsonify(resultado)


@chat_bp.route('/bloqueados', methods=['GET'])
def listar_bloqueados():
    id_usuario_logado = session.get('id_usuario')
    
    bloqueados = UsuarioBloqueado.query.filter_by(id_bloqueador=id_usuario_logado).all()
    resultado = [{
        'nome_usuario': Usuario.query.get(bloqueado.id_bloqueado).nome_usuario,
        'id_usuario': Usuario.query.get(bloqueado.id_bloqueado).id_usuario,
        'foto_perfil': Usuario.query.get(bloqueado.id_bloqueado).foto_perfil
        } for bloqueado in bloqueados]
    
    return jsonify(resultado)


@chat_bp.route('/grupos', methods=['GET'])
def listar_grupos():
    id_usuario_logado = session.get('id_usuario')
    grupos_usuario = MembroGrupo.query.filter_by(id_usuario=id_usuario_logado).all()
    
    resultado = []
    for membro_grupo in grupos_usuario:
        grupo = Grupo.query.get(membro_grupo.id_grupo)
        if grupo:
            membros_count = MembroGrupo.query.filter_by(id_grupo=grupo.id_grupo).count()
            resultado.append({
                'id_grupo': grupo.id_grupo,
                'nome_grupo': grupo.nome_grupo,
                'foto_grupo': grupo.foto_grupo,
                'membros_count': membros_count
            })
    
    return jsonify(resultado)

app/controllers/usuarios_controller.py
from flask import Blueprint, request, jsonify, make_response, render_template, flash, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
import uuid
import os
from app.models.usuario import Usuario, db
from datetime import datetime

from app.decorador import login_obrigatorio # decorador para secao obrigatoria


usuario_bp = Blueprint('usuarios', __name__, url_prefix='/usuarios')

# Registro de novo usuário
@usuario_bp.route('/registrar', methods=['GET', 'POST'])
def registrar():
    if request.method == 'POST':

        usuario = dict(request.form)

        # Verifica se o email ou numero de telefone já existe
        if Usuario.query.filter_by(email=usuario['email']).first() or Usuario.query.filter_by(numero_telefone=usuario['telefone']).first():
            
            flash('Email ou número de telefone já está em uso', 'danger')
            return redirect(url_for('usuarios.registrar'))
            #return "Email ou número de telefone já está em uso"
        
        # Fazer upload da imagem do usuario
        upload_folder = 'app/static/img/usuarios'
        imagem = request.files['imagem']

        if imagem:
            filename = secure_filename(imagem.filename)
            ext = filename.rsplit('.', 1)[1].lower()
            nome_unico_imagem = f"{uuid.uuid4().hex}.{ext}"
            imagem.save(os.path.join(upload_folder, nome_unico_imagem))
        else:
            nome_unico_imagem = 'imagem_usuario_padrao.png'  # Imagem padrão caso nenhuma imagem seja enviada

        # Criar um novo usuário
        hashed_password = generate_password_hash(usuario['senha'])
        novo_usuario = Usuario(
            nome_usuario=usuario['nome'],
            email=usuario['email'],
            numero_telefone=usuario['telefone'],
            senha=hashed_password,
            foto_perfil=nome_unico_imagem,
            status='offline'
        )

        # Guardar na BD
        try:
            db.session.add(novo_usuario)
            db.session.commit()

            flash('Usuário registrado com sucesso!', 'success')
            return redirect(url_for('usuarios.login'))
            #return "Usuário registrado com sucesso!"

        except Exception as e:
            db.session.rollback()
            flash(f'Erro ao registrar usuario: {str(e)}', 'danger')

    return render_template('signup.html')
    

# Login de usuário
@usuario_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':

        usuario = dict(request.form)
        usuario_resultado = Usuario.query.filter_by(email=usuario['email']).first() or Usuario.query.filter_by(numero_telefone=usuario['email']).first()

        if not usuario_resultado or not check_password_hash(usuario_resultado.senha, usuario['senha']):
            
            flash('Credenciais inválidas!', 'danger')
            return redirect(url_for('usuarios.login'))

        session['id_usuario'] = usuario_resultado.id_usuario
        session['nome_usuario'] = usuario_resultado.nome_usuario
        session['imagem_usuario'] = usuario_resultado.foto_perfil
        
        usuario_resultado.status = 'online'
        usuario_resultado.ultimo_visto = datetime.utcnow()
        db.session.commit()

        flash('Login realizado com sucesso!', 'success')
        return redirect(url_for('chat.home'))
        #return 'Login realizado com sucesso!'

    return render_template('login.html')
    

# Atualização do perfil do usuário
@usuario_bp.route('/update', methods=['POST'])
@login_obrigatorio
def update_usuario():
    usuario_id = session.get('id_usuario')
    usuario = Usuario.query.get(usuario_id)

    data = dict(request.form) #dados do usuario passado

    # Atualiza as informações do usuário
    if 'nome' in data:
        usuario.nome_usuario = data['nome']
    if 'email' in data:
        usuario.email = data['email']
    if 'telefone' in data:
        usuario.numero_telefone = data['telefone']
    if 'senha' in data:
        usuario.senha = generate_password_hash(data['senha'])
    if 'imagem' in data:
        usuario.foto_perfil = data['imagem']

    usuario.atualizado_em = datetime.utcnow()
    db.session.commit()

    flash('Perfil atualizado com sucesso!', 'success')
    return render_template('perfil.html', usuario=usuario)

    

# Visualizar informações do perfil
@usuario_bp.route('/perfil/<int:usuario_id>', methods=['GET'])
@login_obrigatorio
def ver_perfil(usuario_id):
    usuario = Usuario.query.get(usuario_id)

    if not usuario:
        flash('Usuário não emcontrado!', 'warning')
        return redirect(url_for('chat.home'))

    return render_template('perfil.html', usuario=usuario)

# Excluir conta de usuário
@usuario_bp.route('/remover', methods=['POST'])
@login_obrigatorio
def remover_usuario():

    usuario_id = session.get('id_usuario')
    usuario = Usuario.query.get(usuario_id)

    if not usuario:
        flash('Usuário não emcontrado!', 'warning')
        return redirect(url_for('usuarios.ver_perfil'))

    db.session.delete(usuario)
    db.session.commit()

    flash('Conta excluída com sucesso!', 'success')
    return redirect(url_for('chat.index'))
    

# Sair e atualizar status do usuário
@usuario_bp.route('/logout', methods=['POST'])
@login_obrigatorio
def logout():

    usuario_id = session.get('id_usuario')

    if not usuario_id:
        flash('Usuário não está logado!', 'warning')
        return redirect(url_for('usuarios.login'))

    usuario = Usuario.query.get(usuario_id)

    if not usuario:
        flash('Usuário não encontrado!', 'danger')
        return redirect(url_for('usuarios.login'))

    usuario.status = 'offline'
    usuario.ultimo_visto = datetime.utcnow()
    db.session.commit()

    # Limpar a sessão
    session.clear()

    flash('Logout realizado com sucesso!', 'success')
    return redirect(url_for('usuarios.login'))
    

# Listar todos os usuários
@usuario_bp.route('/usuarios', methods=['GET'])
@login_obrigatorio
def listar_usuarios():
    
    return render_template('index.html')
   

app/templates/chat.html
{% extends "base.html" %}

    <!-- Head-->
{% block head %}
    <title>ChatXm</title>
{% endblock %}

    <!--Conteudo da tag <body>-->
    {% block body %}

    <div class="container-fluid">
        <div class="row no-gutters">
            <!-- Sidebar -->
            <div id="sidebar" class="col-md-3 col-lg-2 sidebar">
                <div class="header">
                    <a href="{{ url_for('chat.home') }}" class="logo-container">
                        <img src="{{ url_for('static', filename='img/app/logo.png') }}" width="70" class="logo" alt="Logo"></a>
                </div>
                <div class="nav-icons">
                    <a href="#" class="nav-icon active" data-target="all-messages" title="All Messages">
                        <i class="fas fa-inbox"></i>
                    </a>
                    <a href="#" class="nav-icon" data-target="contacts" title="Contacts">
                        <i class="fas fa-address-book"></i>
                    </a>
                    <a href="#" class="nav-icon" data-target="archived" title="Archived">
                        <i class="fas fa-archive"></i>
                    </a>
                    <a href="#" class="nav-icon" data-target="bin" title="Bin">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </div>
                <!-- Pesquisa de contactos -->
                <div class="search-container">
                    <form class="search-form">
                        <input type="text" class="form-control search-input" placeholder="Pesquisar contactos">
                        <button type="submit" class="search-button">
                            <i class="fas fa-search"></i>
                        </button>
                    </form>
                </div>
                <div id="all-messages" class="chat-list active">
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>John Doe <small><i class="fas fa-circle text-success"></i></small>
</h6>
                            <small class="text-dark">Hey, how's it going?</small>
                        </div>
                    </div>
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>John Doe <small><i class="fas fa-circle text-success"></i></small>
</h6>
                            <small class="text-dark">Hey, how's it going?</small>
                        </div>
                    </div>
                </div>
                <div id="contacts" class="chat-list">
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>Alice Johnson</h6>
                            <small class="text-dark">Project Manager</small>
                        </div>
                    </div>
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>Bob Wilson</h6>
                            <small class="text-dark">Developer</small>
                        </div>
                    </div>
                </div>
                <div id="archived" class="chat-list">
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>Carol Taylor</h6>
                            <small class="text-dark">Last message: 2 weeks ago</small>
                        </div>
                    </div>
                </div>
                <div id="bin" class="chat-list">
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>David Brown</h6>
                            <small class="text-dark">Deleted: Yesterday</small>
                        </div>
                    </div>
                </div>
                
                <!-- User Profile -->
                <div class="user-profile">
                    <img src="{{ url_for('static', filename='img/usuarios/' ~ session['imagem_usuario']) }}" alt="User Avatar" class="user-avatar">
                    <span class="user-name">{{session['nome_usuario']}}</span>
                    <i class="fas fa-chevron-up"></i>
                    <div class="user-menu">
                        <a href="{{ url_for('usuarios.ver_perfil', usuario_id=session['id_usuario']) }}" class="menu-item">Perfil</a>
                        <a href="#" class="menu-item">Configurações</a>
                        <form action="{{ url_for('usuarios.logout') }}" method="POST" style="display: inline;">
                            <button type="submit" class="menu-item btn-link w-100">Sair</button>
                        </form>
                    </div>
                </div>
                
            </div>
            <!-- Main Content -->
            <div class="col-md-9 col-lg-10" id="main-content">
                <!-- Dados do usuario participante da conversa -->
                <div class="chat-header d-flex align-items-center bg-success">
                    <button id="sidebar-toggle" class="btn btn-light d-md-none mr-3">
                        <i class="fas fa-bars"></i>
                    </button>
                    <a href="{{ url_for('usuarios.ver_perfil', usuario_id=2) }}">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle mr-2" width="40" alt="User Image">
                    </a>
                    <div>
                        <h5>
                            <a class="text-decoration-none text-dark" href="{{ url_for('usuarios.ver_perfil', usuario_id=session['id_usuario']) }}">
                                Nome usuario a coversar
                            </a>
                            </h5>
                        <small><i class="fas fa-circle text-success"></i> status</small>
                    </div>
                    <div class=" ">
                        <i class="fas fa-search mx-2"></i>
                        <i class="fas fa-phone mx-2"></i>
                        <i class="fas fa-video mx-2"></i>
                        <i class="fas fa-ellipsis-v mx-2"></i>
                    </div>
                </div>
                <div class="chat-body">
                    <p class="small text-muted">Monday, 22 April 2020</p>
                    <div class="message">
                        
                        <div class="d-flex justify-content-start">
                            <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle mr-2" width="25" height="25" alt="User Image">
                            <!-- Mensagem recebida -->
                            <div class="message-content">
                                <p>Great, I'm eager to hear your feedback. We've put a lot of effort into refining these designs.</p>
                                <span class="message-time">09:12 AM</span>
                            </div>
                        </div>
                    </div>
                    <div class="message">
                        <div class="d-flex justify-content-end">
                            <!-- Mensagem enviada -->
                            <div class="message-content sent">
                                <p>Wow, these prototypes look fantastic! I really like the sleek design and the color choices. I think they'll definitely appeal to our target market</p>
                                <span class="message-time">09:14 AM</span>
                            </div>
                            <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle ml-2" width="25" height="25" alt="User Image">
                        </div>
                    </div>
                    <div class="message">
                        <div class="d-flex justify-content-start">
                            <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle mr-2" width="25" height="25" alt="User Image">
                            <!-- Mensagem recebida -->
                            <div class="message-content">
                                <p>Actually, I noticed a small issue with the placement of the logo on the second prototype. It seems a bit off-center. Other than that, everything looks spot on</p>
                                <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="img-thumbnail" alt="Image">
                                <span class="message-time">09:32 AM</span>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Campo para escrever mensagem-->
                <div class="chat-footer">
                    <input type="text" class="form-control" placeholder="Escreva a sua mensagem">
                    <i class="fas fa-paper-plane ml-2"></i>
                </div>
            </div>
        </div>
    </div>
    
    {% endblock %}

    <!--Arquivos Javascript-->
    {% block scriptJS %}

    
    {% endblock %}

app/templates/perfil.html
{% extends "base.html" %}

    <!-- Head-->
{% block head %}
    <title>ChatXm</title>
{% endblock %}

    <!--Conteudo da tag <body>-->
    {% block body %}

    <div class="container-fluid">
        <div class="row no-gutters">
            <!-- Sidebar -->
            <div id="sidebar" class="col-md-3 col-lg-2 sidebar">
                <div class="header">
                    <a href="{{ url_for('chat.home') }}" class="logo-container">
                        <img src="{{ url_for('static', filename='img/app/logo.png') }}" width="70" class="logo" alt="Logo"></a>
                </div>
                <div class="nav-icons">
                    <a href="#" class="nav-icon active" data-target="all-messages" title="All Messages">
                        <i class="fas fa-inbox"></i>
                    </a>
                    <a href="#" class="nav-icon" data-target="contacts" title="Contacts">
                        <i class="fas fa-address-book"></i>
                    </a>
                    <a href="#" class="nav-icon" data-target="archived" title="Archived">
                        <i class="fas fa-archive"></i>
                    </a>
                    <a href="#" class="nav-icon" data-target="bin" title="Bin">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </div>
                <!-- Pesquisa de contactos -->
                <div class="search-container">
                    <form class="search-form">
                        <input type="text" class="form-control search-input" placeholder="Pesquisar contactos">
                        <button type="submit" class="search-button">
                            <i class="fas fa-search"></i>
                        </button>
                    </form>
                </div>
                <div id="all-messages" class="chat-list active">
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>John Doe <small><i class="fas fa-circle text-success"></i></small>
</h6>
                            <small class="text-dark">Hey, how's it going?</small>
                        </div>
                    </div>
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>John Doe <small><i class="fas fa-circle text-success"></i></small>
</h6>
                            <small class="text-dark">Hey, how's it going?</small>
                        </div>
                    </div>
                </div>
                <div id="contacts" class="chat-list">
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>Alice Johnson</h6>
                            <small class="text-dark">Project Manager</small>
                        </div>
                    </div>
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>Bob Wilson</h6>
                            <small class="text-dark">Developer</small>
                        </div>
                    </div>
                </div>
                <div id="archived" class="chat-list">
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>Carol Taylor</h6>
                            <small class="text-dark">Last message: 2 weeks ago</small>
                        </div>
                    </div>
                </div>
                <div id="bin" class="chat-list">
                    <div class="chat-user">
                        <img src="{{ url_for('static', filename='img/usuarios/avatar1.png') }}" class="rounded-circle" alt="User Image">
                        <div class="chat-info">
                            <h6>David Brown</h6>
                            <small class="text-dark">Deleted: Yesterday</small>
                        </div>
                    </div>
                </div>
                
                <!-- User Profile -->
                <div class="user-profile">
                    <img src="{{ url_for('static', filename='img/usuarios/' ~ session['imagem_usuario']) }}" alt="User Avatar" class="user-avatar">
                    <span class="user-name">{{session['nome_usuario']}}</span>
                    <i class="fas fa-chevron-up"></i>
                    <div class="user-menu">
                        <a href="{{ url_for('usuarios.ver_perfil', usuario_id=session['id_usuario']) }}" class="menu-item">Perfil</a>
                        <a href="#" class="menu-item">Configurações</a>
                        <form action="{{ url_for('usuarios.logout') }}" method="POST" style="display: inline;">
                            <button type="submit" class="menu-item btn-link w-100">Sair</button>
                        </form>
                    </div>
                </div>
                
            </div>
            <!-- Main Content -->
            <div class="col-md-9 col-lg-10" id="main-content">
                <div class="chat-header d-flex align-items-center bg-success">
                    <button id="sidebar-toggle" class="btn btn-light d-md-none mr-3">
                        <i class="fas fa-bars"></i>
                    </button>
                    
                    <div class=" ">
                        <i class="fas fa-search mx-2"></i>
                        <i class="fas fa-phone mx-2"></i>
                        <i class="fas fa-video mx-2"></i>
                        <i class="fas fa-ellipsis-v mx-2"></i>
                    </div>
                </div>
                <div class="chat-body">
                    <div class="container mt-4">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="card">
                                    <div class="card-body text-center">
                                        <img src="{{ url_for('static', filename='img/usuarios/' ~ usuario.foto_perfil) }}" class="rounded-circle mb-3" alt="User Avatar" width="150">
                                        <h5 class="card-title">{{ usuario.nome_usuario }}</h5>
                                        <!--<p class="text-muted">Coach</p>-->
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <div class="card">
                                    <div class="card-body">
                                        <div><strong>Nome:</strong> <span>{{ usuario.nome_usuario }}</span></div>
                                        <div><strong>Email:</strong> <span>{{ usuario.email }}</span></div>
                                        <div><strong>Telefone:</strong> <span>{{ usuario.numero_telefone }}</span></div>

                                        {% if session.get('id_usuario') == usuario.id_usuario %}
                                        <div class="mt-5">
                                            <form class="d-inline" action="{{ url_for('usuarios.remover_usuario') }}" method="POST">
                                                <button type="submit" class="btn btn-danger btn-sm">Eliminar Conta</button>
                                            </form>
                                            <button type="button" class="btn btn-outline-success btn-sm" data-bs-toggle="modal" data-bs-target="#modalEditarUsuario">
                                                Editar Usuario
                                            </button>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <h5>Sobre</h5>
                                        <p>Edith is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout...</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

    <!-- Modal Editar Usuario-->
    {% include 'modalEditarUsuario.html' %}
    
    {% endblock %}

    <!--Arquivos Javascript-->
    {% block scriptJS %}

    
    {% endblock %}